### ISSUE TITLE
Transformation error: no value or default function given for field "exported"

### ISSUE THREAD

**Issue by globalexport** [homer0/cjs2esm#25]
Hi, and thanks for this great tool! 

I found an edge case causing it to fail.  Please try out this file: 

```
'use strict'

const v8 = require('v8')
const myClone = (o) => v8.deserialize(v8.serialize(o))

module.exports = { myClone }
``` 

Stacktrace: 
```
ERR /Users/me/projects/customer/project/dev-repo/repos/api/esm/utils.js Transformation error (no value or default function given for field "exported" of ExportSpecifier("id": Identifier | null, "name": Identifier | null))
Error: no value or default function given for field "exported" of ExportSpecifier("id": Identifier | null, "name": Identifier | null)
    at addParam (/Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/types.ts:595:17)
    at /Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/types.ts:635:11
    at Array.forEach (<anonymous>)
    at Function.exportSpecifier (/Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/types.ts:633:37)
    at map (/Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/5to6-codemod@1.8.0/node_modules/5to6-codemod/transforms/named-export-generation.js:187:13)
    at Array.map (<anonymous>)
    at createSpecificedNamedExportDeclaration (/Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/5to6-codemod@1.8.0/node_modules/5to6-codemod/transforms/named-export-generation.js:186:6)
    at NodePath.addNamedExports (/Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/5to6-codemod@1.8.0/node_modules/5to6-codemod/transforms/named-export-generation.js:133:41)
    at /Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/jscodeshift@0.15.1_@babel+preset-env@7.24.5/node_modules/jscodeshift/src/Collection.js:75:36
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/jscodeshift@0.15.1_@babel+preset-env@7.24.5/node_modules/jscodeshift/src/Collection.js:74:18)
    at module.exports (/Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/5to6-codemod@1.8.0/node_modules/5to6-codemod/transforms/named-export-generation.js:222:40)
[cjs2esm] Error: At least one file couldn't be transformed with `named-export-generation`
[cjs2esm] at transformOutput (/Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/cjs2esm@4.0.1/node_modules/cjs2esm/src/index.js:446:11)
[cjs2esm] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[cjs2esm] at async /Users/me/Library/pnpm/store/v3/tmp/dlx-96597/node_modules/.pnpm/cjs2esm@4.0.1/node_modules/cjs2esm/src/bin.js:25:3
[cjs2esm]
[cjs2esm] If the issue persist, create a ticket and I may be able to help you: https://github.com/homer0/cjs2esm/issues/new :D
```

---
Node v20.12.2

**Comment by homer0** [comment]
Hi @globalexport 

Thanks, and sorry it took me so much to answer... there's some config issue between my notifications and my emails filters :(.

I'll try to take a look this weekend and get back to you.

Regards.

**Comment by homer0** [comment]
Hi @globalexport 

I have good news and bad news, sorry... I was able to figure out what causes that issue, but not how to fix it, since this package doesn't actually run transformations, it just puts together a set of tools.

I tried with older dependencies (went back until v3.0.0, 2 years ago), and the issue was still present: You can't override the `module.exports` :(.

You can make your code works if you change this:

```diff
'use strict'

const v8 = require('v8')
const myClone = (o) => v8.deserialize(v8.serialize(o))

- module.exports = { myClone }
+ module.exports.myClone = myClone
```

> That approach also works better for intellisense and jsdoc tooltips.

Just in case, I added a note in the README.

Sorry I couldn't be of more help, I hope the package is still useful for you.

**Comment by globalexport** [comment]
No problem. I manually converted the file. :) 
Your tool was working great in all other cases.
